name: snapshot and generat JSON

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch:

jobs:
  snapshot-json:
    permissions:
      contents: write
    name: snapshot&json
    runs-on: ubuntu-latest
    steps:
      - name: use node 17
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - uses: actions/checkout@v3
      - name: set timezone to America/Los_Angeles
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Los_Angeles"
          timezoneMacos: "America/Los_Angeles"
      - name: list files
        run: tree -L 3 .

      - name: install node dependencies
        working-directory: ./worker
        run: npm install

      - name: take a snapshot&json
        working-directory: ./worker
        run: |
          npm run pipeline:snapshot
          npm run pipeline:datekeys
          npm run pipeline:json

      - name: check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      - name: commit
        if: steps.git-check.outputs.modified == 'true'
        run:  |
          current=$(date)
          git config --global user.name 'dublin-threads-bot'
          git config --global user.email 'dublin-threads@amazingandyyy.com'
          git status
          git add -A
          echo $current
          git commit -m 'feat(data): snapshot and json' -m "$current"
          git push
